# Generated by Django 4.2.6 on 2023-12-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='equipment_name',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='generation_name',
        ),
        migrations.AddField(
            model_name='car',
            name='mark_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='model_name',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
